### ISSUE TITLE
Support multiple EPackages

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emf-cbp#1]
Ideally, a resource should be able to contain instances of EClasses from multiple EPackages. The first time an instance of an EClass of a "new" EPackage is added to a resource, a "new EPackage" event could be registered e.g.

```
epackage http://xyz.com
create A 1 // Create a new instance of A from the 1st EPackage. 
           // Ideally "create A" should also work as we only have one 
           // EPackage registered in the resource so far.
epackage http://foo.com
create B 2 // Create a new instance of B from the 2nd EPackage
create C 1 // Create a new instance of C from the 1st EPackage (http://xyz.com)
```

This would eliminate the need for the ePackage entry in the save options.

**Comment by wrwei** [comment]
Hi Dimitri, I am in the middle of implementing this. At present the serilaised text file has a header, which is made of 
%CBP version number: xxx%
%NAMESPACEURI: xxx%

I guess we just remove the second line?

**Comment by kolovos** [comment]
Yes - the second line should no longer be necessary in the presence of "epackage nsuri" events.

**Comment by wrwei** [comment]
Added a new event called EPackageRegistrationEvent. But there is a potential overhead that a check is performed every time an EObject is added to the resource in the EventAdapter class. All test cases have been modified and all tests have passed.
