### ISSUE TITLE
Generating a minimal CBP-based tree metamodel does not behave as expected

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emf-cbp#10]
I've tried to exercise the textual CBP implementation using the following EOL program that should in principle generate a minimal tree Ecore metamodel:

```
var p = new EPackage;
p.name = "tree";

var tree = new EClass;
tree.name = "Tree";

p.eClassifiers.add(tree);

var children = new EReference;
children.name = "children";
children.eType = tree;
children.upperBound = -1;
tree.eStructuralFeatures.add(children);

var parent = new EReference;
parent.name = "parent";
parent.eType = tree;
parent.lowerBound = 0;
parent.eOpposite = children;
children.eOpposite = parent;
tree.eStructuralFeatures.add(parent);
```

After I run the program above, I can see the generated "tree" EPackage and the "Tree" EClass in Exeed but not the two EReferences. Also, the EClass is not nested under the EPackage as expected but appears as a top-level element.

**Comment by wrwei** [comment]
Issue fixed in commit https://github.com/epsilonlabs/emf-cbp/commit/ae5fab6bd7550825fba2b9a6d16be93122052105

**Comment by agarciadom** [comment]
Closing for now, to keep the issue tracker a bit tidier.
