### ISSUE TITLE
Use enums for SerialisationEventType

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emf-cbp#11]
Right now, SerialisationEventType contains two collections constants: one with strings and another with numbers. Using enumerations that stored the two related values would ensure we don't forget adding verbose versions of the non-verbose numbers, and the Java compiler could detect if we're missing a case in switch statements.

It could also be useful to reduce duplication of code across the two switch statements in CBPTextDeserialiser, for instance.

**Comment by kolovos** [comment]
SerialisationEventType has been deleted
