### ISSUE TITLE
EMF Compare reports odd differences between .cbptext and .xmi model

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emf-cbp#14]
With all the bugfixes we did, I decided to re-run my EMF Compare experiment:

* Create an XMI model with one Tree "root" element.
* Create a .cbptext model with one Tree "root" element.
* Trick EMF Compare into considering .cbptext as XMI for the purposes of comparison, by adding `*.cbptext` to "Preferences -> Content Types -> Text -> XML -> XML Metadata Interchange".
* Select both `onlyRoot.xmi` and `onlyRoot.cbptext` on the Package Explorer, right-click and use "
Compare With -> Each Other".

However, instead of EMF Compare saying that the two models are the same, it's saying that the two roots are completely different from each other.

![screenshot from 2017-02-06 10-36-22](https://cloud.githubusercontent.com/assets/46504/22643846/246c8044-ec58-11e6-9fb9-fec8febe12f3.png)

This used to work in previous EMF CBP versions. In fact, 2 weeks ago I tried doing a three-way comparison between `onlyRoot.xmi`, `onlyRoot.cbptext` and `oneChild.xmi`, and I was able to successfully transplant the changes between the two `.xmi` models to the `.cbptext`.

In case they help, I have also attached the files I used: [example.zip](https://github.com/epsilonlabs/emf-cbp/files/754310/example.zip)

**Comment by kolovos** [comment]
Could the two roots somehow have different IDs?

**Comment by agarciadom** [comment]
This is just the Tree metamodel working from `DynamicEObjectImpl`s, which as far as I understand doesn't use any IDs. It's all rather odd - I guess we'll have to poke at it with a debugger a bit.

**Comment by kolovos** [comment]
This no longer appears to be the case with the new .cbpxml implementation for the following files:

tree.ecore
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Tree"
    nsURI="Tree" nsPrefix="Tree">
  <eClassifiers xsi:type="ecore:EClass" name="Tree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Tree" containment="true" eOpposite="#//Tree/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Tree"
        eOpposite="#//Tree/children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" 
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
```

tree.xmi
```xml
<?xml version="1.0" encoding="ASCII"?>
<Tree:Tree xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:Tree="Tree"/>
```

tree.cbpxml
```xml
<register epackage="Tree"/>
<create eclass="Tree" epackage="Tree" id="0"/>
<add-to-resource position="0"><value eobject="0"/></add-to-resource>
```
