### ISSUE TITLE
Configurable serialisation of names/indexes

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emf-cbp#2]
For debugging purposes it would be nice to be able to serialise class/property names instead of indexes (this could be specified through the options map)

**Comment by wrwei** [comment]
Hi Dimitri, I have implemented CBPVerboseTextSerialiser and CBPVerboseTextDeserialiser for these purposes. These classes introduces minimum change to their original counter parts and eliminate the overhead of if statements checking for debug mode. Test cases have been implemented and all tests have passed. I am closing this ticket now.

**Comment by kolovos** [comment]
Copying-pasting all this code is unlikely to be helpful in terms of maintainability. The overhead of a few if statements should be negligible.

**Comment by wrwei** [comment]
Hi Dimitri, the changes now have been made. All tests have passed.
