### ISSUE TITLE
Avoid using System.exit in plug-in code

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emf-cbp#4]
https://github.com/epsilonlabs/emf-cbp/blob/master/org.eclipse.epsilon.cbp/src/org/eclipse/epsilon/cbp/resource/CBPResource.java#L84

When executed in the context of an Eclipse instance System.exit will close Eclipse without a warning - which is a bit too drastic :)

**Comment by wrwei** [comment]
Indeed, this is the legacy code which I have not looked in depth yet.

**Comment by wrwei** [comment]
Change applied.
